### PR TITLE
Running tests

### PR DESCRIPTION
**Pull request by giorgiosironi**

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Needs credentials for S3, so I'll provide them to the libraries server.

**Comment by giorgiosironi** [comment]
Credentials there but still some permission problem on upload, also I can see a MySQL database is missing. Continuing tomorrow.

**Comment by giorgiosironi** [comment]
I gave to the `elife-libraries` user this Policy:
https://console.aws.amazon.com/iam/home?region=us-east-1#/policies/arn:aws:iam::512686554592:policy/AmazonS3UBRBackupsTestBucketFullAccess
but it seems to to be enough to perform S3 uploads. Anything I should add?

**Comment by giorgiosironi** [comment]
Maybe I was missing a `/*` suffix.

**Comment by giorgiosironi** [comment]
Ok, works with S3, missing MySQL which I'm adding.

**Comment by lsh-0** [comment]
sorry you've been talking to yourself, I need to be pinged or something before I start getting emailed.

> Maybe I was missing a /* suffix.

yes, thats the thing with S3, you need to give it the path and then the path + /* for the path contents.

I've setup permission policies in AWS for accessing the backups, they may need revisiting

**Comment by giorgiosironi** [comment]
This was a custom policy only allowing access to a testing bucket, nothing more needed on IAM side.

**Comment by giorgiosironi** [comment]
Just one test remains failing because of an assertion `1 != 2`, checking it out.

**Comment by giorgiosironi** [comment]
Green after rebasing on `develop`. Still can't run it locally because:
```
Traceback (most recent call last):
  File "/home/giorgio/code/ubr/venv/bin/green", line 11, in <module>
    sys.exit(main())
  File "/home/giorgio/code/ubr/venv/local/lib/python2.7/site-packages/green/cmdline.py", line 18, in main
    args = config.mergeConfig(args, testing)
  File "/home/giorgio/code/ubr/venv/local/lib/python2.7/site-packages/green/config.py", line 393, in mergeConfig
    config = getConfig(getattr(args, 'config', default_args.config))
  File "/home/giorgio/code/ubr/venv/local/lib/python2.7/site-packages/green/config.py", line 372, in getConfig
    read_func(ConfigFile(filepath))
  File "/home/giorgio/code/ubr/venv/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 724, in read_file
    self._read(f, source)
  File "/home/giorgio/code/ubr/venv/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 1035, in _read
    for lineno, line in enumerate(fp, start=1):
TypeError: iter() returned non-iterator of type 'ConfigFile'
```

**Comment by lsh-0** [comment]
hrm - green doesn't like you. tried nuking your venv?

**Comment by giorgiosironi** [comment]
Tried to no avail:
```

[10:57:47][giorgio@Newton:~/code/ubr]$ rm -rf venv
[10:58:01][giorgio@Newton:~/code/ubr]$ ./run-tests.sh
no virtualenv found, creating
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/giorgio/code/ubr/venv/bin/python2
Also creating executable in /home/giorgio/code/ubr/venv/bin/python
Installing setuptools, pip, wheel...done.
activating
Collecting boto3==1.4.3 (from -r requirements.txt (line 1))
  Using cached boto3-1.4.3-py2.py3-none-any.whl
Collecting coverage==4.3.1 (from -r requirements.txt (line 2))
Collecting glob2==0.5 (from -r requirements.txt (line 3))
  Using cached glob2-0.5-py2.py3-none-any.whl
Collecting green==2.5.3 (from -r requirements.txt (line 4))
Collecting ipython==5.1.0 (from -r requirements.txt (line 5))
  Using cached ipython-5.1.0-py2-none-any.whl
Collecting mock==2.0.0 (from -r requirements.txt (line 6))
  Using cached mock-2.0.0-py2.py3-none-any.whl
Collecting pyflakes==1.3.0 (from -r requirements.txt (line 7))
  Using cached pyflakes-1.3.0-py2.py3-none-any.whl
Collecting python-json-logger==0.1.5 (from -r requirements.txt (line 8))
Collecting pylint==1.6.4 (from -r requirements.txt (line 9))
  Using cached pylint-1.6.4-py2.py3-none-any.whl
Collecting PyMySQL==0.7.9 (from -r requirements.txt (line 10))
  Using cached PyMySQL-0.7.9-py2-none-any.whl
Collecting PyYAML==3.12 (from -r requirements.txt (line 11))
Collecting schema==0.6.5 (from -r requirements.txt (line 12))
  Using cached schema-0.6.5-py2.py3-none-any.whl
Collecting jmespath<1.0.0,>=0.7.1 (from boto3==1.4.3->-r requirements.txt (line 1))
  Using cached jmespath-0.9.0-py2.py3-none-any.whl
Collecting s3transfer<0.2.0,>=0.1.10 (from boto3==1.4.3->-r requirements.txt (line 1))
  Using cached s3transfer-0.1.10-py2.py3-none-any.whl
Collecting botocore<1.5.0,>=1.4.1 (from boto3==1.4.3->-r requirements.txt (line 1))
  Using cached botocore-1.4.93-py2.py3-none-any.whl
Collecting colorama (from green==2.5.3->-r requirements.txt (line 4))
  Using cached colorama-0.3.7-py2.py3-none-any.whl
Collecting backports.shutil-get-terminal-size>=1.0.0; python_version == "2.7" (from green==2.5.3->-r requirements.txt (line 4))
  Using cached backports.shutil_get_terminal_size-1.0.0-py2.py3-none-any.whl
Collecting unidecode (from green==2.5.3->-r requirements.txt (line 4))
  Using cached Unidecode-0.04.20-py2.py3-none-any.whl
Collecting python-termstyle (from green==2.5.3->-r requirements.txt (line 4))
Collecting decorator (from ipython==5.1.0->-r requirements.txt (line 5))
  Using cached decorator-4.0.10-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=18.5 in ./venv/lib/python2.7/site-packages (from ipython==5.1.0->-r requirements.txt (line 5))
Collecting pickleshare (from ipython==5.1.0->-r requirements.txt (line 5))
  Using cached pickleshare-0.7.4-py2.py3-none-any.whl
Collecting pygments (from ipython==5.1.0->-r requirements.txt (line 5))
  Using cached Pygments-2.1.3-py2.py3-none-any.whl
Collecting pexpect; sys_platform != "win32" (from ipython==5.1.0->-r requirements.txt (line 5))
  Using cached pexpect-4.2.1-py2.py3-none-any.whl
Collecting pathlib2; python_version == "2.7" or python_version == "3.3" (from ipython==5.1.0->-r requirements.txt (line 5))
  Using cached pathlib2-2.2.0-py2.py3-none-any.whl
Collecting simplegeneric>0.8 (from ipython==5.1.0->-r requirements.txt (line 5))
Collecting prompt-toolkit<2.0.0,>=1.0.3 (from ipython==5.1.0->-r requirements.txt (line 5))
  Using cached prompt_toolkit-1.0.9-py2-none-any.whl
Collecting traitlets>=4.2 (from ipython==5.1.0->-r requirements.txt (line 5))
  Using cached traitlets-4.3.1-py2.py3-none-any.whl
Collecting funcsigs>=1; python_version < "3.3" (from mock==2.0.0->-r requirements.txt (line 6))
  Using cached funcsigs-1.0.2-py2.py3-none-any.whl
Collecting six>=1.9 (from mock==2.0.0->-r requirements.txt (line 6))
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting pbr>=0.11 (from mock==2.0.0->-r requirements.txt (line 6))
  Using cached pbr-1.10.0-py2.py3-none-any.whl
Collecting astroid<1.5.0,>=1.4.5 (from pylint==1.6.4->-r requirements.txt (line 9))
  Using cached astroid-1.4.9-py2.py3-none-any.whl
Collecting configparser; python_version == "2.7" (from pylint==1.6.4->-r requirements.txt (line 9))
Collecting backports.functools-lru-cache; python_version == "2.7" (from pylint==1.6.4->-r requirements.txt (line 9))
  Using cached backports.functools_lru_cache-1.3-py2.py3-none-any.whl
Collecting mccabe (from pylint==1.6.4->-r requirements.txt (line 9))
  Using cached mccabe-0.5.3-py2.py3-none-any.whl
Collecting isort>=4.2.5 (from pylint==1.6.4->-r requirements.txt (line 9))
  Using cached isort-4.2.5-py2.py3-none-any.whl
Collecting futures<4.0.0,>=2.2.0; python_version == "2.6" or python_version == "2.7" (from s3transfer<0.2.0,>=0.1.10->boto3==1.4.3->-r requirements.txt (line 1))
  Using cached futures-3.0.5-py2-none-any.whl
Collecting docutils>=0.10 (from botocore<1.5.0,>=1.4.1->boto3==1.4.3->-r requirements.txt (line 1))
  Using cached docutils-0.13.1-py2-none-any.whl
Collecting python-dateutil<3.0.0,>=2.1 (from botocore<1.5.0,>=1.4.1->boto3==1.4.3->-r requirements.txt (line 1))
  Using cached python_dateutil-2.6.0-py2.py3-none-any.whl
Collecting ptyprocess>=0.5 (from pexpect; sys_platform != "win32"->ipython==5.1.0->-r requirements.txt (line 5))
  Using cached ptyprocess-0.5.1-py2.py3-none-any.whl
Collecting scandir (from pathlib2; python_version == "2.7" or python_version == "3.3"->ipython==5.1.0->-r requirements.txt (line 5))
Collecting wcwidth (from prompt-toolkit<2.0.0,>=1.0.3->ipython==5.1.0->-r requirements.txt (line 5))
  Using cached wcwidth-0.1.7-py2.py3-none-any.whl
Collecting enum34; python_version == "2.7" (from traitlets>=4.2->ipython==5.1.0->-r requirements.txt (line 5))
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting ipython-genutils (from traitlets>=4.2->ipython==5.1.0->-r requirements.txt (line 5))
  Using cached ipython_genutils-0.1.0-py2.py3-none-any.whl
Collecting lazy-object-proxy (from astroid<1.5.0,>=1.4.5->pylint==1.6.4->-r requirements.txt (line 9))
  Using cached lazy_object_proxy-1.2.2-cp27-cp27mu-manylinux1_x86_64.whl
Collecting wrapt (from astroid<1.5.0,>=1.4.5->pylint==1.6.4->-r requirements.txt (line 9))
Installing collected packages: jmespath, futures, docutils, six, python-dateutil, botocore, s3transfer, boto3, coverage, glob2, colorama, backports.shutil-get-terminal-size, unidecode, python-termstyle, funcsigs, pbr, mock, green, decorator, scandir, pathlib2, pickleshare, pygments, ptyprocess, pexpect, simplegeneric, wcwidth, prompt-toolkit, enum34, ipython-genutils, traitlets, ipython, pyflakes, python-json-logger, lazy-object-proxy, wrapt, astroid, configparser, backports.functools-lru-cache, mccabe, isort, pylint, PyMySQL, PyYAML, schema
Successfully installed PyMySQL-0.7.9 PyYAML-3.12 astroid-1.4.9 backports.functools-lru-cache-1.3 backports.shutil-get-terminal-size-1.0.0 boto3-1.4.3 botocore-1.4.93 colorama-0.3.7 configparser-3.5.0 coverage-4.3.1 decorator-4.0.10 docutils-0.13.1 enum34-1.1.6 funcsigs-1.0.2 futures-3.0.5 glob2-0.5 green-2.5.3 ipython-5.1.0 ipython-genutils-0.1.0 isort-4.2.5 jmespath-0.9.0 lazy-object-proxy-1.2.2 mccabe-0.5.3 mock-2.0.0 pathlib2-2.2.0 pbr-1.10.0 pexpect-4.2.1 pickleshare-0.7.4 prompt-toolkit-1.0.9 ptyprocess-0.5.1 pyflakes-1.3.0 pygments-2.1.3 pylint-1.6.4 python-dateutil-2.6.0 python-json-logger-0.1.5 python-termstyle-0.1.10 s3transfer-0.1.10 scandir-1.4 schema-0.6.5 simplegeneric-0.8.1 six-1.10.0 traitlets-4.3.1 unidecode-0.4.20 wcwidth-0.1.7 wrapt-1.10.8
Traceback (most recent call last):
  File "/home/giorgio/code/ubr/venv/bin/green", line 11, in <module>
    sys.exit(main())
  File "/home/giorgio/code/ubr/venv/local/lib/python2.7/site-packages/green/cmdline.py", line 18, in main
    args = config.mergeConfig(args, testing)
  File "/home/giorgio/code/ubr/venv/local/lib/python2.7/site-packages/green/config.py", line 393, in mergeConfig
    config = getConfig(getattr(args, 'config', default_args.config))
  File "/home/giorgio/code/ubr/venv/local/lib/python2.7/site-packages/green/config.py", line 372, in getConfig
    read_func(ConfigFile(filepath))
  File "/home/giorgio/code/ubr/venv/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 724, in read_file
    self._read(f, source)
  File "/home/giorgio/code/ubr/venv/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 1035, in _read
    for lineno, line in enumerate(fp, start=1):
TypeError: iter() returned non-iterator of type 'ConfigFile'
```

**Pull request merged**
