### PR TITLE
Remove GTID from MySQL backup for compatibility with RDS on 5.7.23

### PR DESCRIPTION
**Pull request by giorgiosironi**
See https://github.com/elifesciences/issues/issues/5136

Manually tested from `prod` towards `continuumtest`.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Will extract knowledge from the documentation.

**Comment by giorgiosironi** [comment]
## Theory

- The MySQL server [binary log](https://dev.mysql.com/doc/refman/5.7/en/binary-log.html) contains all events that describe database changes.
  - The binary log can be used for replication of data to MySQL slaves. RDS is [configured with replication](https://aws.amazon.com/rds/details/multi-az/) in `prod` environments.
  - The binary log can be used for point-in-time backup restores where some events from the log are applied to an old backup to make it reach time X. We don't do this at the moment.
- Global Transaction IDs are [identifiers](https://dev.mysql.com/doc/refman/5.7/en/replication-gtids.html) that can be assigned to write transactions on a MySQL master node.
- MySQL slaves nodes can keep a record of the GTIDs that have been applied to their copy of the data.

# Variables

- [`gtid_purged`] is a system variable that contains GTIDs that have been committed, but do not exist in the binary log (anymore, for example because the binary log has been _purged_ aka rotated)
- A dump doesn't contain only data then, but may also contain information about the GTIDs.
- [`--set-gtid-purged=OFF`](https://dev.mysql.com/doc/refman/5.7/en/mysqldump.html#option_mysqldump_set-gtid-purged) does not write GTID-related information to the dump.
  - No ` SET @@GLOBAL.gtid_purged ` statement in the dump
  - No  `@@SESSION.SQL_LOG_BIN=0` statement to disable the binary log 
temporarily
- These properties are problematic because (at least the latter) require `SUPER` privileges, which we don't have on RDS, being a managed server.

# Restore context

When we are restoring, we are not necessarily interested in GTIDs ad we are dropping the database first.
If we were to restore a slave node to bring it on par with master,we could use GTIDs. Unsupported as well as replication is always managed by RDS.

**Comment by lsh-0** [comment]
this makes me laugh, cheers @giorgiosironi . It's good. And thorough.

thorough

**Comment by giorgiosironi** [comment]
I'm just going to merge this on Monday as I don't want an headache on Friday night :sweat_smile:

**Pull request merged**
